### PR TITLE
[ logging ] Make output of build commands logged

### PR DESCRIPTION
**Pull request by buzden**
I believe that sooner or later pack should support some kind of silent mode, when, say, only info or only errors are printed.

But pack runs a lot of other programs which print a lot to the standard output. Despite that mix of prefixed log messages with non-log output subjectively looks non-esthetic, for now there is no way to suppress such outputs depending on, say, configuration.

I propose to manage lines of output asynchronously using recently added system function, and log it, thus giving an ability to manage when those lines should be printed and when not.

Since I couldn't decide which log level to use for this, I've added a new one. I believe that there are situations when this level should be shown and there are situations when should not.

Technically, this PR depends on #178, but not ideologically.

Also, this PR is split into several commits for ease of review. Beside all, it contains small (I think, reasonable) refactoring for beating circular dependency problem.

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
We definitely need a way to silence sys command output, and I wanted to have this almost since the beginning of pack but never got around to implement it properly. Could you please rebase this to `main`, now that #178 has been merged. I'll give it a go on my system afterwards.

**Comment by buzden** [comment]
Sure! Rebased

**Comment by buzden** [comment]
> So, here is an issue I found with this: Command line output of build commands is no longer printed when it comes up, but only once the command has finished. For instance, if I run `pack build` on an `.ipkg`, the log is silent unless the build has finished, instead of printing the files it builds whenever they come up. Any idea if there is an easy fix for this?

OMG, this is something unintended. Before starting to implement this PR, I checked that `runProcessingOutput` allows to print lines along execution of a command simultaneously. Let's see what's happening... At least, I checked that flushing doesn't help

**Comment by buzden** [comment]
> Any idea if there is an easy fix for this?

The problem is that command we run is allowed to not to buffer its output and it happened that I tested `sysAndLog` behaviour only on non-buffering commands. The only way I know to turn on line buffering is `stdbuf` command from `coreutils`. There is a fix that uses this: #182. However, I'm not sure when and where `stdbuf` is available. Say, it's likely to be on any GNU machine, but I don't know if it's available, say, on Mac machines.

**Comment by stefan-hoeck** [comment]
> > Any idea if there is an easy fix for this?
> 
> The problem is that command we run is allowed to not to buffer its output and it happened that I tested `sysAndLog` behaviour only on non-buffering commands. The only way I know to turn on line buffering is `stdbuf` command from `coreutils`. There is a fix that uses this: #182. However, I'm not sure when and where `stdbuf` is available. Say, it's likely to be on any GNU machine, but I don't know if it's available, say, on Mac machines.

OK, I'll check with the Mac users on discord whether they have `stdbuf` available on their machines. Thanks again for your incredible help!

**Pull request merged**
