### PR TITLE
Add docker build and publish ci workflow

### PR DESCRIPTION
**Pull request by alexhumphreys**
I haven't tested the publish part, but it is similar to one I have used previously.

Also wasn't sure on which events this should run (branch/push/schedule), and what schedule it should run, so any input here would be good.

The hardcoded default value of `DB ?= nightly-220604` in the makefile ain't great, but `date` has very different flags for trying to print yesterday's date on linux vs mac, so I bumped it and left it for now.

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
So, here I are a couple of thoughts and questions as I'm unfortunately still rather unfamiliar with Docker:

* If I understand this correctly, this will create a Docker container (is that the word?) with pack available. Will this also have the corresponding Idris compiler prebuilt and installed?
* Package collection nightlies are created and tested daily at 1 am GitHub time (whatever that means; looks like the corresponding action runs around 5 am in the morning where I live, which is UTC +2 during summer time). This takes about half an hour, so I guess it would make sense to build the Docker container a couple of hours after that.
* micropack should choose the latest nightly on its own. This is something I was planning to fix anyway.

So, I suggest I'll first fix micropack, so we will no longer have to hard-code the nightly to use. What do you think?

**Comment by alexhumphreys** [comment]
> This will create a Docker container (is that the word?) with pack available. Will this also have the corresponding Idris compiler prebuilt and installed?

Correct, this will have both idris and pack built and installed. Word wise it's called a docker image. The thing that's running when you do `docker run` is a container, and containers are based on images.
> created and tested daily at 1 am GitHub time

Github time seems to be [UTC](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule). Something seems odd if that's 5am for you, but I'm bad at timeszones 😅 Either way, if it's 1am github time if i set this to 5am it should be ok?

> micropack should choose the latest nightly on its own. This is something I was planning to fix anyway.

Ah right! Well i need that YYMMDD var outside of micropack so that I can add the correct tag to the docker image, so maybe it's good to just specify it so we're sure the one micropack builds matches the tag... or were you referring to the value in the `Makefile`?

**Comment by stefan-hoeck** [comment]
In that case, I'll leave micropack for the time being.

**Comment by stefan-hoeck** [comment]
> Github time seems to be [UTC](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule). Something seems odd if that's 5am for you, but I'm bad at timeszones sweat_smile Either way, if it's 1am github time if i set this to 5am it should be ok?

Yes, that's what I thought too, that's why I'm rather confused why the check runs so late. Well, important thing is that it runs at all.

**Comment by alexhumphreys** [comment]
Ok think I finally appeased the linter 😅 
Just realised the timing I guess if I'm building yesterday's package set I have like 24 hours for it to run, so the timing should be ok. Could try build the latest nightly then it's a little more tight.

**Comment by stefan-hoeck** [comment]
The current build failure is related to the changes regarding the package path I'm working. I think I fixed that by now, so a rebase should be enough to get this to pass, but lets wait for the collection test I'm running at the moment. This should show whether all is fine now.

**Comment by alexhumphreys** [comment]
Ah cool, will see how it behaves with that fix.

Just updated the schedule/`date` so that it runs with the latest `nightly-*` build. No point waiting 24 hours for our sweet new dependencies.

**Comment by alexhumphreys** [comment]
https://github.com/stefan-hoeck/idris2-pack/pull/83 am I right that after this micropack no longer accepts a `DB` param? If so I'll remove that from this PR. Would make a few things easier, though could happen that we end up with a docker image tagged with a day and a different package set is inside... which is technically correct in the sense that the _docker image_ was built at the day it says it was, even if it then contains a _package set_ from different day :D

**Comment by stefan-hoeck** [comment]
> #83 am I right that after this micropack no longer accepts a `DB` param? If so I'll remove that from this PR. Would make a few things easier, though could happen that we end up with a docker image tagged with a day and a different package set is inside... which is technically correct in the sense that the _docker image_ was built at the day it says it was, even if it then contains a _package set_ from different day :D

micropack still accepts a DB param, but this is now optional. The Makefile, however, no longer passes on the `DB` variable to micropack. We could reintroduce this, if you prefer it that way.

micropack had several issues, both with the current change to use shell wrappers with package paths set for executables like LSP or the compiler itself. But it was also unreliable, because the glibc version to use was "hardcoded", because a prebuilt version of `libidris2_support.so` was bundled with it.

I changed this, so that `libidris2_support.so` is now built at the installation site when invoking the makefile.

But here is another thought: Would it make sense to add this action to the pack-db project, where it could be run right after creating the nightly? Then the two things would always run in quick succession. Also, if checking the package collection fails (due to one or more failing packages), no new nightly is created at the moment (but `STATUS.md` is still updated). In that case, we wouldn't want a new docker image either, right?

**Comment by alexhumphreys** [comment]
I think I'm ok with not passing the DB param explicitly. Should that cause issues down the line we can change it.

As regards where this action should live, the main reason I put it here is for naming. Think when hosting the docker image on github the name has to match the repo name. So here we get a nice `idris2-pack` docker image name, whereas `idris2-pack-db` is a little unwieldy. You're right that it'd be much more convenient if it was in the idris2-pack-db repo though.

**Comment by stefan-hoeck** [comment]
Fair enough. Do you think this is ready for merging then? We can still adjust it later on if there is any need.

**Comment by alexhumphreys** [comment]
Yeah, I think it's good to go. Will probably find some more issues but I can fix those as we run into them 👍

**Comment by stefan-hoeck** [comment]
Thanks again for this.

**Pull request merged**
