### PR TITLE
Install curl in CI

### PR DESCRIPTION
**Pull request by joelberkeley**

### CODE REVIEW

**Comment by buzden** [comment]
Any clue why?

**Comment by joelberkeley** [comment]
@buzden I don't understand the question. spidr requires curl to install so does pack's primary installation route. I don't know the full reasons, but stefan suggested we add curl to the builds https://discord.com/channels/827106007712661524/841274390481600562/1249031320399773738

**Comment by joelberkeley** [comment]
I must admit I'm only confident, not certain, it's a good idea myself. curl is a reasonably lightweight dependency that will exist on most user systems

Perhaps I shouldn't add it to the Dockerfile since not everything requires it. Even spidr is very explicit that it's a build dependency ... yeah I'll remove it there

**Comment by joelberkeley** [comment]
I guess the danger is that someone's installation requires curl but doesn't say it does, passes in pack-db CI, then fails when someone tried tried to install it. TBH that seems like a pretty small problem

**Comment by joelberkeley** [comment]
this whole PR was a misunderstanding. stefan meant in pack-db not here

**Pull request closed without merging**
