### PR TITLE
[ feat ] cmd `run` and `exec` support for node backend

### PR DESCRIPTION
**Pull request by running-grass**
resole #156

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
In case no user-defined codegen is given, you should try to extract the corresponding setting from the `.ipkg` file in scope.

**Comment by running-grass** [comment]
> you should try to extract the corresponding setting from the `.ipkg` file in scope.

@stefan-hoeck  i don't know how to implementation。😓

**Comment by stefan-hoeck** [comment]
I finally got around to adding support for `.ipkg` codegen options. However, this branch has diverged from the pack main branch. Could you please rebase this. Then we should be ready to merge.

**Comment by running-grass** [comment]
> I finally got around to adding support for `.ipkg` codegen options. However, this branch has diverged from the pack main branch. Could you please rebase this. Then we should be ready to merge.

Done.

**Pull request merged**
