### PR TITLE
Add "new" command for package creation [WIP]

### PR DESCRIPTION
**Pull request by trevarj**
Added a "new" command which can be invoked with `pack new lib mylib` or
`pack new bin myapp`. This will create a directory with the supplied
package name and also create a `src/` dir, template .ipkg file, and
either a Main.idr or [MyLib].idr.

This is still a work in progress, since there are a few nuances to
decide on and iron out.

### CODE REVIEW

**Comment by trevarj** [comment]
Just a friendly warning - I am new to Idris. I would like to start a few project using it, so I figured a nice way to get my feet wet is by helping out with something in the ecosystem. 

I would be grateful for any feedback and recommendations to make my code more idiomatic! Thanks!

**Comment by trevarj** [comment]
A few notes about the current implementation of `pack new`:
- If you misspell `lib` or `bin` after `new`, it will default to `lib` (perhaps this could be resolved with a more robust command line args parser?)
- I am unsure if there should be more things added to the generated .ipkg file

**Comment by stefan-hoeck** [comment]
Sorry for not replying earlier. I have been offline for three days. I like the idea and will look at this tonight.

**Comment by alexhumphreys** [comment]
Just a heads up in case you ain't aware, there is an `idris2 --init` flag you can pass:
```
  --init [package file]                       Interactively initialise a new project
```
Won't give you the default `Main` module that you have here, but maybe this flag or the functions powering it could be of some use.

**Comment by trevarj** [comment]
@alexhumphreys 🤦🏻‍♂️ can't believe I didn't check `idris2` for that...thanks!

Perhaps I should just have it use that command. I also thought that it might be nice to automatically init a git project and provide an idris .gitignore

**Comment by stefan-hoeck** [comment]
This looks really nice. Perhaps you could mention in the command's help text that it will also initialize a new git repository.

**Comment by stefan-hoeck** [comment]
@trevarj Do you think there is still something important missing with this? Otherwise I think I'll merge this and we can optimize/adjust it later on if there is any need.

**Comment by trevarj** [comment]
@stefan-hoeck I think it's ok for now. I have been using it with a few small projects I am working on. If you don't see anything that stands out with the logic or general idris, we can merge. Thanks!

**Comment by stefan-hoeck** [comment]
I updated this to the latest changes in the main branch and will merge it now. Thanks again for your contribution!

**Pull request merged**
