### PR TITLE
add install shell script

### PR DESCRIPTION
**Pull request by thomasdziedzic**
fixes https://github.com/stefan-hoeck/idris2-pack/issues/48

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
Personally, I think `python3` is a bit of a hefty dependency. We could small `sed` scripts to extract the desired hashes from the `.toml` files. Here's how to do this for the `toml-idr` hash: Put the following content in file `toml-idr.sed`:

```sed
/^\[db.toml\]/,/^commit/{
  /^commit/s/commit *= *"\([a-f0-9]*\)"/\1/p
}
```
and extract the commit hash from `nightly-220519.toml` with the following command:

```sh
sed -nf toml-idr.sed nightly220519.toml
```.

What do you think?

Also, please note that the scheme executable is not always called `chezscheme` on all systems. On my system, it's just `scheme`, so the name of this executable should somehow be asked from the user.

**Comment by stefan-hoeck** [comment]
This can even be done without putting the sed commands in a script:

```sh
FOO=$(sed -ne '/^\[db.toml\]/,/^commit/{/^commit/s/commit *= *"\([a-f0-9]*\)"/\1/p}' nightly-220519.toml)
```

**Comment by thomasdziedzic** [comment]
> What do you think?

I don't like using regular expressions to substitute parsing formats, but let's go with it so that we don't rely on python3 being installed for now. There could be problems on macos and other platforms with sed due to it being from bsd instead of gnu but we'll get there once someone tests this on macos.

> Also, please note that the scheme executable is not always called chezscheme on all systems. On my system, it's just scheme, so the name of this executable should somehow be asked from the user.

Added autodetection along with a prompt for the scheme binary.

**Comment by stefan-hoeck** [comment]
This is looking great! I'll give it a go tonight an will report back here.

**Comment by stefan-hoeck** [comment]
I just ran the script on my system. Two things I observed:

* It wasn't possible to customize the installation directory for *pack*. If environment variable `$PACK_DIR` is set, *pack* should be installed there (this would also allow me to keep my existing *pack* installation).
* The nightly it chose was `nightly-220508`. I would expect it to use the latest nightly.

Other than that, it worked like a charm!

**Comment by thomasdziedzic** [comment]
> It wasn't possible to customize the installation directory for pack. If environment variable $PACK_DIR is set, pack should be installed there (this would also allow me to keep my existing pack installation).

Added another prompt to ask the user for a pack directory, similar to what I did for scheme.

> The nightly it chose was nightly-220508. I would expect it to use the latest nightly.

This was a regression due to me trying to make shellcheck happy. Added a change that should now select the latest db.

**Comment by stefan-hoeck** [comment]
Great! Testing it now.

**Comment by stefan-hoeck** [comment]
I thinks this almost ready for merging. I have only two remaining nitpicks:

  * Could we remove the `clones` directory after installation?
  * Instead of asking for the `$PACK_DIR`, the install script should check whether the corresponding variable is set. Users want to use a custom directory for `pack` will have to set this variable anyway.

**Comment by thomasdziedzic** [comment]
> Could we remove the clones directory after installation?

done

> Instead of asking for the $PACK_DIR, the install script should check whether the corresponding variable is set. Users want to use a custom directory for pack will have to set this variable anyway.

done. users will have to set the variable before invoking the script due to how the shell works

```
$ ./install.bash 
+ PACK_DIR=/home/tom/.pack
$ PACK_DIR=/home/tom/.pack2 ./install.bash
+ PACK_DIR=/home/tom/.pack2
```

**Comment by stefan-hoeck** [comment]
Thanks a lot for your help with this. I'll merge this now, and I'll test it on a couple of people at work. If all goes we'll, we can added official documentation and drop micropack.

**Comment by thomasdziedzic** [comment]
Your welcome! It was great collaborating with you on this feature!

**Pull request merged**
