### PR TITLE
[ new ] Support non-toplevel `pack.toml` files

### PR DESCRIPTION
**Pull request by buzden**
Implements #185. I couldn't resist trying to implement this, and in the case I originally described it works as I expect. Generally, feel free to close it as soon as you think it's not worth having.

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
Thanks for this. One question I have: I think it can indeed be useful to consider all `pack.toml` files in all parent directories with the closer ones taking precedence over the ones further away. However, do we need the new config option for this, aka, is there really a need to specify in `pack.toml` files whether to stop at the current position or move further upwards, given that local setting take precedence anyway?

**Comment by buzden** [comment]
> However, do we need the new config option for this, aka, is there really a need to specify in `pack.toml` files whether to stop at the current position or move further upwards, given that local setting take precedence anyway?

The original intent of this option was to preserve precisely the same behaviour in the case when there are no changes to the config files. But, indeed, maybe this is just an extra complication. I don't see cases when this behaviour would ruin something.

**Comment by stefan-hoeck** [comment]
So, if you think that's a valid option, I suggest we drop the additional config field and just add support for merging `pack.toml` files from all parent directories.

**Comment by buzden** [comment]
Yeah, I did it. This also changed the order we parse local TOML files when there are several (it influences on the errors order, since we quit on the first parsing error, but I thought that's okay anyway). Also, I've tweaked `logMany` to support the mode of logging that was there previously, while preserving previous usages unchanged.

**Comment by stefan-hoeck** [comment]
Thanks for this! I think this is easy enough to understand and explain, while adding some convenience when managing deeply nested multi-package projects.

**Pull request merged**
