### PR TITLE
Arm64macos

### PR DESCRIPTION
**Pull request by berewt**
It's still a bit ugly as I used Dunham tricks to rename the .dylib in a .so, but it's now working on my machine and its still passing the build.
I'm not sure if it's mature enough for a merge but we're getting closer to it at least.

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
Thanks a lot for this. Just tell me once you think this is ready. I'll also ping @dunhamsteve , because you discussed this on discord.

**Comment by berewt** [comment]
Thank you for pack actually! Noe thing I still have to check with @dunhamsteve is his comment about the different Mac architecture. I think the use of lipo is not needed as the right dylib/so is actually generated at build time but I may have missed something.
If he thinks it's okay, we can probably merge it.

**Comment by stefan-hoeck** [comment]
Before merging this it would be great if you could also add a note to the installation instructions. I'd probably get this all wrong if I tried to do it myself.

**Comment by dunhamsteve** [comment]
The lipo thing would only be needed if we were distributing binaries and wanted a single binary that worked on both macos architectures. I didn’t know if the end goal here was a binary distribution of micropack.

**Comment by stefan-hoeck** [comment]
I'm going to merge this, then. Thanks a lot for adding this (and updating the docs).

**Pull request merged**
