### PR TITLE
[ new ] pack-admin: Show help when no argument is given

### PR DESCRIPTION
**Pull request by locriacyber**
Previously, running `pack-admin` shows no sign of how to use it.

I thought of printing usage on error, but I can't seem to get `EitherT` to do what I want.

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
> Previously, running `pack-admin` shows no sign of how to use it.
> 
> I thought of printing usage on error, but I can't seem to get `EitherT` to do what I want.

For printing usage on error, you can use `catchError` from `Control.Monad.Error.Interface` in base. Make sure to only print usage info in case of errors related to invalid command line args.

**Comment by locriacyber** [comment]
After inspecting the code, this is a good enough. Adding more code is messy.

**Comment by stefan-hoeck** [comment]
I think this is ready to go then once the linter is happy. Could you please look into this?

**Comment by locriacyber** [comment]
@stefan-hoeck I think now I need approval, where as previous I don't

**Comment by stefan-hoeck** [comment]
This has been superseded by #195

**Pull request closed without merging**
